name: SAX-VSM
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
baseurl: /sax-vsm_site
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Algorithm
  # - Outcomes
  - Pattern Analysis
  - Classification
  - Clustering
  #- Assessments
  #- Schedule

# The following properties are optional.
# See the User Guide (http://morea-framework.github.io/userguide.html) for more info.

# morea_course: ics311
# morea_domain: http://morea-framework.github.io/
# morea_google_analytics_tracking_id: "<your tracking id here>"

#morea_head_breadcrumb_link: "http://cnn.com"
#morea_head_breadcrumb_label: "CNN Site"